# ---------------- #
#   Main Configs   #
# ---------------- #
#baseurl: https://comsince.github.io
url: https://www.comsince.cn
date_format: "ordinal"
title: 我的comsince技术小站
subtitle: "坚持分享，分享快乐"
description: "坚持分享，分享快乐"
keywords: comsince, yurenfei
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: comsince
organization: Meizu, Inc.
organization_url: https://www.meizu.com
location: zhuhai, China
email: ljlong2009@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /open-source/
    label: 开源
    
  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
paginate_path: "/blog/page:num/"
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: comsince/comsince.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: comsince
douban_username: comsince
facebook_username: comsince
weibo_username: comsince
zhihu_username: comsince
twitter_username: comsince

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo,gittalk
comments_provider: gittalk
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: comsince
disqus_username: comsince
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: false

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: comsince
    repo: comsince_blog_comment
    clientID: 28ca83cafae12f7540a6
    clientSecret: 23f34cef588f07a40d702af14dfb662eb89b1e41

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: G-9NL9BTD41Z

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Groovy, Design Patterns]
skill_mobile_app_keywords: [Android, J2EE Engineering]
skill_windows_keywords: [Java, Android]
