apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: mysql-db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: push-group-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-db
spec:
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - args:
        - mysqld
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        env:
        - name: MYSQL_PASSWORD
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_USER
          value: test
        name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim    
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper-servicefind
spec:
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
  selector:
    app: zookeeper-servicefind
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper-servicefind
spec:
  template:
        metadata:
          labels:
            app: zookeeper-servicefind
        spec:
          containers:
          - env:
            - name: TZ
              value: Asia/Shanghai        
            name: zookeeper
            image: zookeeper:3.5.5
            ports:
              - containerPort: 2181
                name: zookeeper            
---
apiVersion: v1
kind: Service
metadata:
  name: push-connector
  labels:
    app: push-connector-dubbo
spec:
  ports:
    - port: 6789
      nodePort: 30789
      targetPort: 6789
      name: push-connector
  selector:
    app: push-connector-dubbo
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: push-connector
  labels:
    app: push-connector-dubbo
spec:
  template:
    metadata:
      labels:
        app: push-connector-dubbo
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai         
        name: push-connector
        image: comsince/push-connector
        ports:
          - containerPort: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: push-group
  labels:
    app: push-group-web
spec:
  ports:
    - port: 8081
      nodePort: 30081
      targetPort: 8081
      name: push-group
  selector:
    app: push-group-web
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: push-group
  labels:
    app: push-group-web
spec:
  template:
    metadata:
      labels:
        app: push-group-web
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai         
        name: push-group
        image: comsince/push-group
        ports:
          - containerPort: 8081
