version: '2'
services:

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
      MYSQL_USER: test   #创建test用户
      MYSQL_PASSWORD: test  #设置test用户的密码
    ports:
      - '3306:3306'
    networks:
      - universe-push

  zookeeper:
    environment:
      TZ: Asia/Shanghai
    image: zookeeper:3.5.5
    restart: always
    ports:
      - 2181:2181
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - universe-push

  push-connector:
    environment:
      TZ: Asia/Shanghai
    image: comsince/push-connector
    restart: always
    depends_on:
      - zookeeper
      - push-group
    ports:
      - 6789:6789
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - universe-push

  push-group:
    environment:
      TZ: Asia/Shanghai
    image: comsince/push-group
    restart: always
    depends_on:
      - zookeeper
      - mysql
    ports:
      - 8081:8081
      - 7463:7463
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - universe-push

networks:
  universe-push:
    driver: bridge
