name: Build and Deploy Jekyll

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll
        run: bundle exec jekyll build

      # - name: Upload to server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     #这里的private key 是本地生成的，然后自己本地服务ssh，成功之后，进行远程服务登录，然后将本地的privatekey保存到github变量中
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       rsync -azv --delete comsince.github.io/_site/ /data/boot/comsince.cn


      - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        with:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete # rsync参数，排除.pyc文件
          SERVER_PORT: '22' # SSH端口
          FOLDER: _site/ # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SERVER_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SERVER_USERNAME }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /data/boot/comsince.cn # 部署到目标文件夹            

      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            nginx -t
            nginx -s reload