name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.x

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll
        run: bundle exec jekyll build

      - name: Upload to server
        run: |
          sudo apt-get install -y rsync
          echo "${{ secrets.SERVER_PASSWORD }}" > password.txt
          rsync -azv --delete --password-file=password.txt _site/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/data/boot/comsince.cn

      - name: Reload Nginx
        run: sudo nginx -s reload
